package ru.iandreyshev.jokesfeed.ui.filter

import ru.iandreyshev.jokesfeed.domain.Topic

fun Topic.name() = when (this) {
    Topic.OFFICE -> "офис"
    Topic.GOSSIP -> "болтун"
    Topic.ANIMALS -> "животные"
    Topic.COMPUTERS -> "компьютеры"
    Topic.SCIENTISTS -> "учёные"
    Topic.FOOD -> "еда"
    Topic.JOKES -> "игра_слов"
    Topic.MATHEMATICAL -> "математика"
    Topic.GHOSTS -> "призраки"
    Topic.MEDICINE -> "медицина"
    Topic.SPORT -> "спорт"
    Topic.VAMPIRES -> "вампиры"
    Topic.BOOKS -> "книги"
    Topic.BALLS -> "шары"
    Topic.ROBOTS -> "роботы"
    Topic.PLANETS -> "планеты"
    Topic.EASTER -> "пасха"
    Topic.FLOWERS -> "цветы"
    Topic.CLOCKS -> "часы"
    Topic.TEAPOT -> "чайник"
    Topic.CLOTHING -> "одежда"
    Topic.LIGHTBULB -> "лампочка"
    Topic.FRUITS -> "фрукты"
    Topic.METALS -> "матыллы"
    Topic.VEGETABLES -> "овощи"
    Topic.STATIONERY -> "канцелярия"
    Topic.TECHNOLOGY -> "технологии"
    Topic.DAYSOFWEEK -> "дни_недели"
    Topic.SEA -> "море"
    Topic.BOWLING -> "боулинг"
    Topic.DRINKS -> "напитки"
    Topic.CLOUDS -> "облака"
    Topic.MONTHS -> "месяцы"
}
